apiVersion: apps/v1

kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql:3306 # wp-2. mysql pod의 3306을 매치한다는 의미인듯(?), mysql > template > spec > port부분 이름 바꿔서 똑같이 되는지 테스트 해보기
            - name: WORDPRESS_DB_NAME
              value: k8sdb
            - name: WORDPRESS_DB_USER
              value: k8suser
            - name: WORDPRESS_DB_PASSWORD
              value: P@ssw0rd!!
          ports:
            - containerPort: 80
              name: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-volumeclaim