apiVersion: v1
kind: Service
metadata:
  name: fluent-bit-service
  namespace: alp-mgmt-fluentbit
spec:
  type: ClusterIP
  selector:
    k8s-app: fluent-bit-logging
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224