apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mynginx
  template:
    metadata:
      labels:
        run: mynginx
    spec:
      containers:
        - image: 3.38.108.115/cloudclub/junggyu:latest
          name: mynginx
          ports:
            - containerPort: 80
