name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker login 3.38.108.115 -u admin -p Harbor12345

        # image 세팅
      - name: Docker meta
        run: docker tag mariadb 3.38.108.115/cloudclub/mymariadb:0.2

        # Harbor Push
      - name: Push Harbor
        run: docker push 3.38.108.115/cloudclub/mymariadb:0.2
#         uses : docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           platforms: linux/amd64
#           push: true
