name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ master ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        run: docker login ${{ secrets.HARBOR_ADDRESS }} -u ${{ secrets.HARBOR_USERNAME }} -p ${{ secrets.HARBOR_PASSWORD }}

      - name: Build
        # uses: actions/python~~~~~~
        run: ./gradlew # 애플리케이션 Build

      - name: Container Image Build
        run: docker build . -t cloud-native

        # image 세팅
      - name: Docker meta
        run: docker tag mariadb ${{ secrets.HARBOR_ADDRESS}}//cloud-native:0.5

        # Harbor Push
      - name: Push Harbor
        run: docker push ${{ secrets.HARBOR_ADDRESS}}${{ secrets.HARBOR_REPOSITORY}}cloud-native:0.5
